### ISSUE TITLE
Unsatisfiable dependencies with conda-bld

### ISSUE THREAD

**Issue by adamcpovey** [conda-forge/netcdf-fortran-feedstock#56]
Issue:
I can't build packages that depend on `netcdf-fortran`. As a test, I tried the following `meta.yaml` file with a blank `build.sh`:
```yaml
package:
    name: nullpackage
    version: 1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - libnetcdf
    - netcdf-fortran
  run:
    - libnetcdf
    - netcdf-fortran
```

It works if I remove the `netcdf-fortran` lines. With them the output is:
```
(base) machine:~$ conda-build --override-channels -c conda-forge -c anaconda --no-anaconda-upload ~/tmp/nullpackage --numpy 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for nullpackage
INFO:conda_build.metadata:Attempting to finalize metadata for nullpackage
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                  

Leaving build/test directories:
  Work:
 /home/freshconda/conda-bld/work 
  Test:
 /home/freshconda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/freshconda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/freshconda/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/environ.py", line 787, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/freshconda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/freshconda/lib/python3.8/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/freshconda/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/freshconda/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/freshconda/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/freshconda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/freshconda/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/home/freshconda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/freshconda/lib/python3.8/site-packages/conda/resolve.py", line 1321, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/home/freshconda/lib/python3.8/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libnetcdf conflicts for:
netcdf-fortran -> libnetcdf[version='*|*|*|>=4.7.4,<4.7.5.0a0|>=4.7.4,<4.7.5.0a0|>=4.7.4,<4.7.5.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.1,<4.7.2.0a0|>=4.7.1,<4.7.2.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.1,<4.7.2.0a0|>=4.7.1,<4.7.2.0a0|>=4.6.2,<4.6.3.0a0|>=4.7.1,<5.0a0|>=4.7.0,<4.7.1.0a0|>=4.6.2,<4.7.0a0|>=4.6.2,<5.0a0',build='mpi_openmpi_*|mpi_mpich_*|mpi_mpich_*|nompi_*|mpi_mpich_*|mpi_openmpi_*|nompi_*|mpi_openmpi_*|mpi_mpich_*|nompi_*|mpi_openmpi_*']
libnetcdf

Package libgcc-ng conflicts for:
netcdf-fortran -> openmpi[version='>=4.0.4,<4.1.0a0'] -> libgcc-ng[version='>=9.3.0']
libnetcdf -> mpich[version='>=3.3,<3.4.0a0'] -> libgcc-ng[version='>=9.3.0']
netcdf-fortran -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0']
libgcc-ng[version='>=9.3.0']
libnetcdf -> libgcc-ng[version='7.2.0.*|>=4.9|>=7.3.0|>=7.5.0|>=7.2.0']

Package libgfortran5 conflicts for:
libgfortran5[version='>=9.3.0']
libnetcdf -> mpich[version='>=3.3,<3.4.0a0'] -> libgfortran5[version='>=9.3.0']
netcdf-fortran -> openmpi[version='>=4.0.4,<4.1.0a0'] -> libgfortran5[version='>=9.3.0']

Package libstdcxx-ng conflicts for:
libnetcdf -> hdf4[version='>=4.2.13,<4.3.0a0'] -> libstdcxx-ng[version='7.2.0.*|>=4.9|>=7.3.0|>=7.2.0|>=7.5.0|>=9.3.0']
netcdf-fortran -> hdf5=[build=nompi_*] -> libstdcxx-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']
libstdcxx-ng[version='>=9.3.0']

Package libgfortran-ng conflicts for:
netcdf-fortran -> libgfortran-ng[version='>=7,<8.0a0']
libgfortran-ng
libnetcdf -> hdf5=[build=nompi_*] -> libgfortran-ng[version='7.2.0.*|>=4.9|>=7,<8.0a0|>=7.2.0|>=7.2.0,<8.0a0']
netcdf-fortran -> openmpi[version='>=4.0.4,<4.1.0a0'] -> libgfortran-ng

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/freshconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/build.py", line 3000, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/build.py", line 1968, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/render.py", line 757, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/metadata.py", line 2062, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/metadata.py", line 735, in finalize_outputs_pass
    fm = finalize_metadata(om, parent_metadata=parent_metadata,
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/render.py", line 531, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/render.py", line 406, in add_upstream_pins
    host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/render.py", line 371, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/render.py", line 139, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/home/freshconda/lib/python3.8/site-packages/conda_build/environ.py", line 789, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"libgfortran-ng[version='>=7,<8.0a0']", "libstdcxx-ng[version='7.2.0.*|>=4.9|>=7.3.0|>=7.2.0|>=7.5.0|>=9.3.0']", "libgcc-ng[version='7.2.0.*|>=4.9|>=7.3.0|>=7.5.0|>=7.2.0']", "libstdcxx-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']", "libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0']", 'libgfortran-ng', "libnetcdf[version='*|*|*|>=4.7.4,<4.7.5.0a0|>=4.7.4,<4.7.5.0a0|>=4.7.4,<4.7.5.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.1,<4.7.2.0a0|>=4.7.1,<4.7.2.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.3,<4.7.3.1.0a0|>=4.7.1,<4.7.2.0a0|>=4.7.1,<4.7.2.0a0|>=4.6.2,<4.6.3.0a0|>=4.7.1,<5.0a0|>=4.7.0,<4.7.1.0a0|>=4.6.2,<4.7.0a0|>=4.6.2,<5.0a0',build='mpi_openmpi_*|mpi_mpich_*|mpi_mpich_*|nompi_*|mpi_mpich_*|mpi_openmpi_*|nompi_*|mpi_openmpi_*|mpi_mpich_*|nompi_*|mpi_openmpi_*']", "libgfortran-ng[version='7.2.0.*|>=4.9|>=7,<8.0a0|>=7.2.0|>=7.2.0,<8.0a0']", "libgcc-ng[version='>=9.3.0']", "libgfortran5[version='>=9.3.0']"}
```

<br/>
Environment (<code>conda list</code>):

<details>
I made a completely new conda install in a local folder using the following:

```sh
PREFIX=/home/freshconda
TMPDIR=$(mktemp -d)
pushd $TMPDIR
wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
chmod 0700 Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh -b -p "$PREFIX"
. "$PREFIX"/etc/profile.d/conda.sh
popd
rm -rf $TMPDIR
conda activate
conda update -y -c conda-forge -c anaconda --all
conda install -y -c conda-forge -c anaconda conda-build conda-verify
```

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h924ce5b_2    conda-forge
cffi                      1.14.3           py38h1bdcb99_1    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
conda                     4.8.5            py38h924ce5b_2    conda-forge
conda-build               3.20.3           py38h32f6830_0    conda-forge
conda-package-handling    1.7.0            py38h8df0ef7_6    conda-forge
conda-verify              3.1.1           py38h32f6830_1001    conda-forge
cryptography              3.1.1            py38h766eaa4_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
future                    0.18.2           py38h32f6830_2    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libarchive                3.4.3                hf837322_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.10.1               he1b5a44_2    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py38h8df0ef7_2    conda-forge
ncurses                   6.2                  he1b5a44_2    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pip                       20.2.3                     py_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.7.2            py38h8df0ef7_1    conda-forge
py-lief                   0.10.1           py38h348cfbe_2    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-libarchive-c       2.9              py38h924ce5b_2    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_0    conda-forge
ruamel_yaml               0.15.80         py38h8df0ef7_1003    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tqdm                      4.50.2             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(base) machine:~$ conda info

     active environment : base
    active env location : /home/freshconda
            shell level : 1
       user config file : /home/.condarc
 populated config files : /home/.condarc
          conda version : 4.8.5
    conda-build version : 3.20.3
         python version : 3.8.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/freshconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/mutirri/linux-64
                          https://conda.anaconda.org/mutirri/noarch
                          https://conda.anaconda.org/avalentino/linux-64
                          https://conda.anaconda.org/avalentino/noarch
          package cache : /home/freshconda/pkgs
                          /home/.conda/pkgs
       envs directories : /home/freshconda/envs
                          /home/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.8.6 Linux/4.15.0-118-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 14623:403
             netrc file : /home/.netrc
           offline mode : False

```
</details>

**Comment by chrisburr** [comment]
I probably don't have time to look further but to add more information:
```bash
conda render --override-channels -c conda-forge -c anaconda --no-anaconda-upload . --numpy 1.16
```

```yaml
--------------
Hash contents:
--------------
{'c_compiler': 'gcc', 'cxx_compiler': 'gxx', 'fortran_compiler': 'gfortran'}
----------
meta.yaml:
----------
package:
    name: nullpackage
    version: '1'
build:
    number: '0'
requirements:
    build:
        - sysroot_linux-64 2.12 h77966d4_13
        - _libgcc_mutex 0.1 conda_forge
        - binutils_linux-64 2.35 hc3fd857_29
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - gfortran_impl_linux-64 9.3.0 h2bb4189_17
        - gcc_impl_linux-64 9.3.0 h28f5a38_17
        - gcc_linux-64 9.3.0 h7247604_29
        - gxx_impl_linux-64 9.3.0 h53cdd4c_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-devel_linux-64 9.3.0 h4084dd6_17
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - gxx_linux-64 9.3.0 h0d07fa4_29
        - libgfortran5 9.3.0 he4bcb1c_17
        - gfortran_linux-64 9.3.0 ha1c937c_29
        - libgcc-devel_linux-64 9.3.0 hfd08b2a_17
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ld_impl_linux-64 2.35 h769bd43_9
        - _openmp_mutex 4.5 1_gnu
    host:
        - libgcc-ng >=9.3.0
        - libgfortran5 >=9.3.0
        - netcdf-fortran
        - libnetcdf
        - libgfortran-ng
        - libstdcxx-ng >=9.3.0
    run:
        - libgcc-ng >=9.3.0
        - libgfortran5 >=9.3.0
        - netcdf-fortran
        - libnetcdf
        - libgfortran-ng
        - libstdcxx-ng >=9.3.0
extra:
    copy_test_source_files: true
    final: true
```

Solving the host environment with `mamba`:
```bash
$ mamba create --name test2 --override-channels -c anaconda -c conda-forge --strict-channel-priority  "libgcc-ng >=9.3.0" "libgfortran5 >=9.3.0" "netcdf-fortran" "libnetcdf" "libgfortran-ng" "libstdcxx-ng >=9.3.0"

Encountered problems while solving.
Problem: package netcdf-fortran-4.4.5-h5535e0c_0 requires hdf5 >=1.10.4,<1.10.5.0a0, but none of the providers can be installed
```

And simplifying further:
```bash
mamba create --name test2 --override-channels -c anaconda -c conda-forge --strict-channel-priority  "libgfortran5 >=9.3.0" "netcdf-fortran"

Encountered problems while solving.
Problem: package netcdf-fortran-4.4.5-h5535e0c_0 requires hdf5 >=1.10.4,<1.10.5.0a0, but none of the providers can be installed
```

**Comment by chrisburr** [comment]
I suspect you need a force conda-build to use GCC 7

**Comment by beckermr** [comment]
Yes @chrisburr. In all feedstock builds this is done by our global pinnings file + smithy.

**Comment by adamcpovey** [comment]
Right. Is a more sensible solution to hardcode the version number into my own feedstock (which is easy but feels wrong) or to adopt whatever @beckermr mentioned (which sounds robust but I've been having problems with conda obsoleting my code by the time I return to it and losing a week I don't have to spare)? If the latter, where can I find instructions? 

(Apologies - I am but a lowly scientist trying to generate a robust means for naive users to avoid compiling my numerous dependencies; many bits of the conda-build/forge documentation are over my head. Your patience is greatly appreciated.)

**Comment by chrisburr** [comment]
The simplest solution is probably to add your package to conda-forge if you can? It doesn't matter if it's niche and only useful for a handful of people, it just needs a license that gives conda-forge permission to distribute it (any commonly known open source license is fine).

**Comment by beckermr** [comment]
> The simplest solution is probably to add your package to conda-forge if you can? It doesn't matter if it's niche and only useful for a handful of people, it just needs a license that gives conda-forge permission to distribute it (any commonly known open source license is fine).

This is by far the best thing!

**Comment by adamcpovey** [comment]
Sadly, I legally can't distribute some of my dependencies unless I personally know the recipient has signed the license. (They say they're working on it.)

**Comment by xylar** [comment]
I would say your next best option is to create (and personally maintain) your version of the pinning files that are used on conda-forge, e.g.: https://github.com/conda-forge/netcdf-fortran-feedstock/blob/master/.ci_support/linux_mpinompi.yaml

These come from: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml
and would have to be updated from time to time to stay in sync with conda-forge.

I've done this for my own packages, but it's definitely less fun that having conda-forge do it for you automatically.

You point `conda build` to the file with the appropriate pins with the `-m` option.

@beckermr and @chrisburr, does this sound like good advice to you?  If not, by all means correct me.

**Comment by beckermr** [comment]
Yup. I do this for some projects myself.

**Comment by chrisburr** [comment]
> Sadly, I legally can't distribute some of my dependencies unless I personally know the recipient has signed the license. (They say they're working on it.)

I sympathise, I've been slowly pushing for getting a license added to something for over two years.

I do exactly the same as @xylar suggests (make sure to drop the `--numpy`).

**Comment by adamcpovey** [comment]
I shall get on with that tomorrow. Thanks!

**Comment by xylar** [comment]
@adamcpovey, is there something we still need to address here?  If so, feel free to re-open and comment.

**Comment by adamcpovey** [comment]
Working out how to pin correctly fixed a lot of my problems and I can now build all of my dependencies. The feedstocks are stored on my project's repository, but I remain hesitant to add anything to the forge as I don't want to take on the responsibility of maintenance or compiling for systems I'm not using. And I'm almost certainly doing things wrong as I am a lowly scientist rather than person that knows what to do with code.
